language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm
      dist: trusty
  include:
    - php: hhvm
      dist: trusty

before_script:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then ./vendor/bin/phpunit; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
